# Generated by Django 4.1 on 2022-12-26 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('users', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(default='upload/user.png', upload_to='upload')),
                ('bio', models.TextField(blank=True)),
                ('date_register', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_register'],
            },
        ),
    ]
